name: TicTacToe build app

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          cd src
          javac -classpath . com/kroeger/TicTacToe.java
          jar cfm TicTacToe.jar manifest.mf com/kroeger/TicTacToe.class
          zip TicTacToe.zip TicTacToe.jar
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: ./TicTacToe.zip
          asset_name: TicTacToe.zip
          asset_content_type: application/zip
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: TicTacToe was builded
          to: maya.alina.kroeger@stud.th-luebeck.de
          from: Maya Alina Kröger
          secure: true
          body: Build job of TicTacToe completed successfully! TicTacToe is compiled!
