name: TicTacToe build app

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: javac -classpath . src/com/kroeger/TicTacToe.java
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: TicTacToe was builded
          to: maya.alina.kroeger@stud.th-luebeck.de
          from: Maya Alina Kröger
          secure: true
          body: Build job of TicTacToe completed successfully!
