name: TicTacToe build app

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          cd src
          javac -classpath . com/kroeger/TicTacToe.java
          jar cfm TicTacToe.jar manifest.mf com/kroeger/TicTacToe.class
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: TicTacToe was builded
          to: maya.alina.kroeger@stud.th-luebeck.de
          from: Maya Alina Kröger
          secure: true
          body: Build job of TicTacToe completed successfully! TicTacToe is compiled!
